### ISSUE TITLE
# Open_IM/internal/rpc/rtc ../../../internal/rpc/rtc/rtcLiveKit.go:66:36: cannot use rpc (variable of type *rtcLiveKit) as type "Open_IM/pkg/proto/rtc".RtcServiceServer in argument to rtc.RegisterRtcServiceServer: 	*rtcLiveKit does not implement "Open_IM/pkg/proto/rtc".RtcServiceServer (missing SignalGetRooms method)

### ISSUE THREAD

**Issue by simanlx** [shoyu666/Open-IM-Server-Call#2]
# Open_IM/internal/rpc/rtc
../../../internal/rpc/rtc/rtcLiveKit.go:66:36: cannot use rpc (variable of type *rtcLiveKit) as type "Open_IM/pkg/proto/rtc".RtcServiceServer in argument to rtc.RegisterRtcServiceServer:
	*rtcLiveKit does not implement "Open_IM/pkg/proto/rtc".RtcServiceServer (missing SignalGetRooms method)

**Comment by shoyu666** [comment]
解决方案：您可以使用 Open_IM-Server 老的版本

原因：Open_IM-Server 源分支在 9月28号提交的代码，增加了 SignalGetRooms方法 
[提交记录](https://github.com/OpenIMSDK/Open-IM-Server/commit/249d5e27887391253547519cd177d766e77a7f00#diff-33db5c101b755c6d95d5eb12faa1165ea82556dbe0d5d969ad73f87a6c7eceb7)

需要使用新版的,可以解注释 rtcLiveKit.go SignalGetRooms 方法。
目前Open_IM-Server版本  SignalGetRooms 方法实际没有用到,可能后续版本这个方法会被用到。
