### ISSUE TITLE
忙线处理有思路吗?

### ISSUE THREAD

**Issue by simanlx** [shoyu666/Open-IM-Server-Call#4]
我在客户端实现忙线处理，但是由于网络原因发现存在很大问题， 看来只能在服务器端实现通话中缓存，是在livekit 缓存好还是在openim 端

**Comment by shoyu666** [comment]
@simanlx  hi,没有仔细的思考过忙线处理逻辑。
“客户端实现忙线” 是指？ “网络原因发现存在很大问题” 是指？

这里可以探讨下初步思路：
im端处理，因为个人觉得这个是信令的逻辑，而livekit是视频逻辑。
A客户端发送请求音视频信令，im接收后发给B,B收到后，判断自己已经处于视频状态，则返回im服务器为忙，im服务器转发给A。

**Comment by simanlx** [comment]
我就是这么实现的，如果用户网络状态不佳 或者离线 问题会很严重

**Comment by simanlx** [comment]
看了livekit 有获取参与者方法  想在呼叫时获取 id是否是livekit参与者来判断是否连线 ，结果也存在问题 如果有两个id同时呼叫一个id是不行的， 没办法了只能用redis 缓存了！

**Comment by shoyu666** [comment]
> 我就是这么实现的，如果用户网络状态不佳 或者离线 问题会很严重

你是指,B的网络不佳，A等B反馈占线太久了是么？

"如果有两个id同时呼叫一个id是不行的" ？ 这个会出现什么问题？


如果 A呼叫B,im先判断是否占线，直接反馈，如果不占线，连线B。 这个思路可以在im端维护这个关系。
具体可以使用 livekit的 webhook api ，im被动监听livekit的变化，来更新redis缓存。

https://docs.livekit.io/guides/webhooks/
```
interface WebhookEvent { //房间开始
  event: 'room_started'
  room: Room
}

interface WebhookEvent { //房间结束
  event: 'room_finished'
  room: Room
}

interface WebhookEvent { // 参与者加入
  event: 'participant_joined'
  room: Room
  participant: ParticipantInfo
}

interface WebhookEvent {// 参与者离开
  event: 'participant_left'
  room: Room
  participant: ParticipantInfo
}

...
```

**Comment by simanlx** [comment]
no  是a呼叫c  b也同时呼叫c   b 呼叫是占线的 就和微信一样

**Comment by simanlx** [comment]
太麻烦了 ，我 用redis 缓存了！
